### ISSUE TITLE
Auth, GateWay Refactor

### ISSUE THREAD

**Issue by jabberwocker04** [ch2-sparta-team-project/ch2-sparta-logistics#29]
## Description
기능 구현 이후 디테일하게 수정해야되는 부분(생성, 수정, 삭제 시간 혹은 GateWay .yml 파일 수정) 수정 진행하겠습니다.
### Todo
- [x] GateWay .yml파일의 각 서비스 route에 -service 붙이는 방식으로 수정
- [x] 삭제된 유저 조회 구현시, 삭제된 유저와 삭제되지 않은 유저를 isDeleted로 구분하여 조회할 수 있도록 구현
- [x] userId의 UUID 생성 방법 수정
- [x] createdAt, createdBy... Auditing 기능 추가
