### ISSUE TITLE
Product CRUD

### ISSUE THREAD

**Issue by strongcookdas** [ch2-sparta-team-project/ch2-sparta-logistics#3]
## Description
- product create, read, update, delete 구현
- 다른 도메인과 연동은 추후 다른 이슈를 통해 구현
### Todo
- [x] product 프로젝트 설정
- [x] create
- [x] read - 단일 조회
- [x] read - 리스트 조회
- [x] update
- [x] delete
