### ISSUE TITLE
Hub CRUD

### ISSUE THREAD

**Issue by yshong1998** [ch2-sparta-team-project/ch2-sparta-logistics#5]
## Description
Hub CRUD, Search 기능 구현

### Todo
- [ ] Hub 프로젝트 설정
- [ ] Hub Create
- [ ] Hub Read - 단일 조회
- [ ] Hub Read - 목록 조회
- [ ] Hub Update
- [ ] Hub Delete
