### ISSUE TITLE
Product, AI, Config README 작성

### ISSUE THREAD

**Issue by strongcookdas** [ch2-sparta-team-project/ch2-sparta-logistics#64]
## Description
REAMD.md 작성
### Todo
- [x] Proudct REAMD.md 작성
- [x] Config REAMD.md 작성
- [x] AI REAMD.md 작성
