### ISSUE TITLE
Hub, Company, Order, delivery 환경 설정

### ISSUE THREAD

**Issue by yshong1998** [ch2-sparta-team-project/ch2-sparta-logistics#67]
## Description
Config 서버를 기본으로 설정하기 위해 build.gradle과 yml 파일을 수정해야 합니다.
각각에 Swagger 적용이 필요합니다
### Todo
- [ ] 각 도메인마다 build.gradle에 config 관련 의존성 추가
- [ ] 각 도메인마다 yml 파일 config server에서 받아오도록 수정
- [ ] 각 도메인마다 swagger 적용
