### ISSUE TITLE
Product 유효성 로직, Role prefix 삭제, 패키지 구조 변경

### ISSUE THREAD

**Issue by strongcookdas** [ch2-sparta-team-project/ch2-sparta-logistics#77]
## Description
- Product 리팩토링
### Todo
- [x] 유효성 검사 로직
- [x] Role prefix 삭제
- [x] 패키지 구조 변경
