### ISSUE TITLE
Company 엔티티에서 username 필드 제거, auth에서 받아오는 형식으로 변경

### ISSUE THREAD

**Issue by yshong1998** [ch2-sparta-team-project/ch2-sparta-logistics#80]
## Description
Company 엔티티에서 username 필드 제거, auth에서 받아오는 형식으로 변경
### Todo
- [x] Company 엔티티에서 username 필드 제거
- [x] username을 auth에서 받아오는 형식으로 변경
  - [x] 수정 -> company server에서 username을 반환하지 않는 것으로 변경
- [ ] Company 생성, 수정 시 hub의 존재 여부를 조회하는 검증 로직 추가
